// Auth
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

// Movies
export const MOVIES_RETRIEVE_START = 'MOVIES_RETRIEVE_START'
export const MOVIES_RETRIEVE_SUCCESS = 'MOVIES_RETRIEVE_SUCCESS'
export const MOVIES_RETRIEVE_FAILED = 'MOVIES_RETRIEVE_SUCCESS'
export const MOVIES_RETRIEVE_END = 'MOVIES_RETRIEVE_END'
